// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MoodLens.ApiGateway.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MoodLens.ApiGateway.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260429225652_InitialSchema")]
    partial class InitialSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "pgcrypto");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MoodLens.ApiGateway.Models.AnalysisFeedback", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<int>("AnalysisAccuracyRating")
                        .HasColumnType("integer")
                        .HasColumnName("analysis_accuracy_rating");

                    b.Property<string>("Comment")
                        .HasColumnType("text")
                        .HasColumnName("comment");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("GuestSessionId")
                        .HasColumnType("text")
                        .HasColumnName("guest_session_id");

                    b.Property<bool>("Helpful")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("helpful");

                    b.Property<Guid>("HistoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("history_id");

                    b.Property<int>("OverallRating")
                        .HasColumnType("integer")
                        .HasColumnName("overall_rating");

                    b.Property<int>("RecommendationQualityRating")
                        .HasColumnType("integer")
                        .HasColumnName("recommendation_quality_rating");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<bool>("WouldReuse")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("would_reuse");

                    b.HasKey("Id");

                    b.HasIndex("GuestSessionId");

                    b.HasIndex("HistoryId")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("analysis_feedback", t =>
                        {
                            t.HasCheckConstraint("CK_analysis_feedback_accuracy_rating", "\"analysis_accuracy_rating\" BETWEEN 1 AND 5");

                            t.HasCheckConstraint("CK_analysis_feedback_overall_rating", "\"overall_rating\" BETWEEN 1 AND 5");

                            t.HasCheckConstraint("CK_analysis_feedback_recommendation_rating", "\"recommendation_quality_rating\" BETWEEN 1 AND 5");
                        });
                });

            modelBuilder.Entity("MoodLens.ApiGateway.Models.EmotionHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<double>("Confidence")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("double precision")
                        .HasDefaultValue(0.0)
                        .HasColumnName("confidence");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("DetectedEmotion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("detected_emotion");

                    b.Property<string>("Explanation")
                        .HasColumnType("text")
                        .HasColumnName("explanation");

                    b.Property<bool>("FaceDetected")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("face_detected");

                    b.Property<string>("GuestSessionId")
                        .HasColumnType("text")
                        .HasColumnName("guest_session_id");

                    b.Property<string>("ImagePath")
                        .HasColumnType("text")
                        .HasColumnName("image_path");

                    b.Property<string>("ModalityUsed")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("modality_used");

                    b.Property<string>("ModelUsed")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("model_used");

                    b.Property<int?>("ResponseTimeMs")
                        .HasColumnType("integer")
                        .HasColumnName("response_time_ms");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("UserText")
                        .HasColumnType("text")
                        .HasColumnName("user_text");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("GuestSessionId");

                    b.HasIndex("UserId");

                    b.ToTable("emotion_history", t =>
                        {
                            t.HasCheckConstraint("CK_emotion_history_owner", "\"user_id\" IS NOT NULL OR \"guest_session_id\" IS NOT NULL");
                        });
                });

            modelBuilder.Entity("MoodLens.ApiGateway.Models.Recommendation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("category");

                    b.Property<string>("Content")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("content")
                        .HasDefaultValueSql("'{}'::jsonb");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<Guid>("HistoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("history_id");

                    b.HasKey("Id");

                    b.HasIndex("Category");

                    b.HasIndex("HistoryId");

                    b.ToTable("recommendations", t =>
                        {
                            t.HasCheckConstraint("CK_recommendations_category", "\"category\" IN ('music', 'movie', 'book', 'advice')");
                        });
                });

            modelBuilder.Entity("MoodLens.ApiGateway.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("text")
                        .HasColumnName("avatar_url");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("email");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("users");
                });

            modelBuilder.Entity("MoodLens.ApiGateway.Models.AnalysisFeedback", b =>
                {
                    b.HasOne("MoodLens.ApiGateway.Models.EmotionHistory", "EmotionHistory")
                        .WithMany("FeedbackEntries")
                        .HasForeignKey("HistoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MoodLens.ApiGateway.Models.User", "User")
                        .WithMany("FeedbackEntries")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("EmotionHistory");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MoodLens.ApiGateway.Models.EmotionHistory", b =>
                {
                    b.HasOne("MoodLens.ApiGateway.Models.User", "User")
                        .WithMany("EmotionHistories")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("User");
                });

            modelBuilder.Entity("MoodLens.ApiGateway.Models.Recommendation", b =>
                {
                    b.HasOne("MoodLens.ApiGateway.Models.EmotionHistory", "EmotionHistory")
                        .WithMany("Recommendations")
                        .HasForeignKey("HistoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EmotionHistory");
                });

            modelBuilder.Entity("MoodLens.ApiGateway.Models.EmotionHistory", b =>
                {
                    b.Navigation("FeedbackEntries");

                    b.Navigation("Recommendations");
                });

            modelBuilder.Entity("MoodLens.ApiGateway.Models.User", b =>
                {
                    b.Navigation("EmotionHistories");

                    b.Navigation("FeedbackEntries");
                });
#pragma warning restore 612, 618
        }
    }
}
