// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MoodLens.ApiGateway.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MoodLens.ApiGateway.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "pgcrypto");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MoodLens.ApiGateway.Models.AnalysisFeedback", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<int>("AnalysisAccuracyRating")
                        .HasColumnType("integer")
                        .HasColumnName("analysis_accuracy_rating");

                    b.Property<string>("Comment")
                        .HasColumnType("text")
                        .HasColumnName("comment");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("GuestSessionId")
                        .HasColumnType("text")
                        .HasColumnName("guest_session_id");

                    b.Property<bool>("Helpful")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("helpful");

                    b.Property<Guid>("HistoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("history_id");

                    b.Property<int>("OverallRating")
                        .HasColumnType("integer")
                        .HasColumnName("overall_rating");

                    b.Property<int>("RecommendationQualityRating")
                        .HasColumnType("integer")
                        .HasColumnName("recommendation_quality_rating");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<bool>("WouldReuse")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("would_reuse");

                    b.HasKey("Id");

                    b.HasIndex("GuestSessionId");

                    b.HasIndex("HistoryId")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("analysis_feedback", t =>
                        {
                            t.HasCheckConstraint("CK_analysis_feedback_accuracy_rating", "\"analysis_accuracy_rating\" BETWEEN 1 AND 5");

                            t.HasCheckConstraint("CK_analysis_feedback_overall_rating", "\"overall_rating\" BETWEEN 1 AND 5");

                            t.HasCheckConstraint("CK_analysis_feedback_recommendation_rating", "\"recommendation_quality_rating\" BETWEEN 1 AND 5");
                        });
                });

            modelBuilder.Entity("MoodLens.ApiGateway.Models.AnalysisRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<bool>("ConflictDetected")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("conflict_detected");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<double>("EmotionConfidence")
                        .HasColumnType("double precision")
                        .HasColumnName("emotion_confidence");

                    b.Property<Guid?>("EmotionHistoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("emotion_history_id");

                    b.Property<string>("EmotionResult")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("emotion_result");

                    b.Property<double?>("ImageConfidence")
                        .HasColumnType("double precision")
                        .HasColumnName("image_confidence");

                    b.Property<string>("ImageEmotion")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("image_emotion");

                    b.Property<string>("InputType")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("input_type");

                    b.Property<string>("Language")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasDefaultValue("tr")
                        .HasColumnName("language");

                    b.Property<string>("PersonalitySnapshot")
                        .HasColumnType("jsonb")
                        .HasColumnName("personality_snapshot");

                    b.Property<string>("RecommendationsJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("recommendations_json")
                        .HasDefaultValueSql("'{}'::jsonb");

                    b.Property<string>("SessionId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("session_id");

                    b.Property<string>("ShareToken")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("share_token");

                    b.Property<DateTime?>("ShareTokenExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("share_token_expires_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasDefaultValue("complete")
                        .HasColumnName("status");

                    b.Property<double?>("TextConfidence")
                        .HasColumnType("double precision")
                        .HasColumnName("text_confidence");

                    b.Property<string>("TextEmotion")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("text_emotion");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("EmotionHistoryId")
                        .IsUnique()
                        .HasFilter("\"emotion_history_id\" IS NOT NULL");

                    b.HasIndex("SessionId");

                    b.HasIndex("ShareToken")
                        .IsUnique()
                        .HasFilter("\"share_token\" IS NOT NULL");

                    b.HasIndex("ShareTokenExpiresAt");

                    b.HasIndex("UserId");

                    b.ToTable("analysis_records", t =>
                        {
                            t.HasCheckConstraint("CK_analysis_records_emotion_result", "\"emotion_result\" IN ('happy', 'sad', 'angry', 'anxious', 'excited', 'calm', 'tired', 'stressed', 'nostalgic', 'motivated', 'hopeful', 'overwhelmed')");

                            t.HasCheckConstraint("CK_analysis_records_input_type", "\"input_type\" IN ('image', 'text', 'both')");

                            t.HasCheckConstraint("CK_analysis_records_status", "\"status\" IN ('complete', 'partial', 'failed')");
                        });
                });

            modelBuilder.Entity("MoodLens.ApiGateway.Models.EmotionHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<double>("Confidence")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("double precision")
                        .HasDefaultValue(0.0)
                        .HasColumnName("confidence");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("DetectedEmotion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("detected_emotion");

                    b.Property<string>("Explanation")
                        .HasColumnType("text")
                        .HasColumnName("explanation");

                    b.Property<bool>("FaceDetected")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("face_detected");

                    b.Property<string>("GuestSessionId")
                        .HasColumnType("text")
                        .HasColumnName("guest_session_id");

                    b.Property<string>("ImagePath")
                        .HasColumnType("text")
                        .HasColumnName("image_path");

                    b.Property<string>("ModalityUsed")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("modality_used");

                    b.Property<string>("ModelUsed")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("model_used");

                    b.Property<int?>("ResponseTimeMs")
                        .HasColumnType("integer")
                        .HasColumnName("response_time_ms");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("UserText")
                        .HasColumnType("text")
                        .HasColumnName("user_text");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("GuestSessionId");

                    b.HasIndex("UserId");

                    b.ToTable("emotion_history", t =>
                        {
                            t.HasCheckConstraint("CK_emotion_history_owner", "\"user_id\" IS NOT NULL OR \"guest_session_id\" IS NOT NULL");
                        });
                });

            modelBuilder.Entity("MoodLens.ApiGateway.Models.PersonalityUpdateLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("TriggerSource")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("trigger_source");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UpdatedAt");

                    b.HasIndex("UserId");

                    b.ToTable("personality_update_logs");
                });

            modelBuilder.Entity("MoodLens.ApiGateway.Models.Recommendation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("category");

                    b.Property<string>("Content")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("content")
                        .HasDefaultValueSql("'{}'::jsonb");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<Guid>("HistoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("history_id");

                    b.HasKey("Id");

                    b.HasIndex("Category");

                    b.HasIndex("HistoryId");

                    b.ToTable("recommendations", t =>
                        {
                            t.HasCheckConstraint("CK_recommendations_category", "\"category\" IN ('music', 'movie', 'book', 'advice')");
                        });
                });

            modelBuilder.Entity("MoodLens.ApiGateway.Models.SavedRecommendation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid?>("AnalysisRecordId")
                        .HasColumnType("uuid")
                        .HasColumnName("analysis_record_id");

                    b.Property<string>("ItemData")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("item_data")
                        .HasDefaultValueSql("'{}'::jsonb");

                    b.Property<string>("ItemId")
                        .IsRequired()
                        .HasMaxLength(240)
                        .HasColumnType("character varying(240)")
                        .HasColumnName("item_id");

                    b.Property<string>("ItemTitle")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("item_title");

                    b.Property<string>("ItemType")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("item_type");

                    b.Property<DateTime>("SavedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("saved_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("AnalysisRecordId");

                    b.HasIndex("UserId", "ItemType");

                    b.HasIndex("UserId", "ItemType", "ItemId")
                        .IsUnique();

                    b.ToTable("saved_recommendations", t =>
                        {
                            t.HasCheckConstraint("CK_saved_recommendations_item_type", "\"item_type\" IN ('music', 'film', 'book')");
                        });
                });

            modelBuilder.Entity("MoodLens.ApiGateway.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("text")
                        .HasColumnName("avatar_url");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("email");

                    b.Property<string>("EnergyPreference")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("energy_preference");

                    b.Property<string>("FavoriteBookGenres")
                        .HasColumnType("text")
                        .HasColumnName("favorite_book_genres");

                    b.Property<string>("FavoriteMovieGenres")
                        .HasColumnType("text")
                        .HasColumnName("favorite_movie_genres");

                    b.Property<string>("FavoriteMusicGenres")
                        .HasColumnType("text")
                        .HasColumnName("favorite_music_genres");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("PreferredColorTheme")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasDefaultValue("kirmizi")
                        .HasColumnName("preferred_color_theme");

                    b.Property<string>("RecommendationGoal")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("recommendation_goal");

                    b.Property<string>("SpotifyAccessToken")
                        .HasColumnType("text")
                        .HasColumnName("spotify_access_token");

                    b.Property<string>("SpotifyRefreshToken")
                        .HasColumnType("text")
                        .HasColumnName("spotify_refresh_token");

                    b.Property<DateTime?>("SpotifyTokenExpiry")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("spotify_token_expiry");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("users");
                });

            modelBuilder.Entity("MoodLens.ApiGateway.Models.UserMediaLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("LoggedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("logged_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Note")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("note");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(240)
                        .HasColumnType("character varying(240)")
                        .HasColumnName("title");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("type");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("LoggedAt");

                    b.HasIndex("UserId");

                    b.ToTable("user_media_log", t =>
                        {
                            t.HasCheckConstraint("CK_user_media_log_type", "\"type\" IN ('film', 'book')");
                        });
                });

            modelBuilder.Entity("MoodLens.ApiGateway.Models.UserPersonalityProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("AgeGroup")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("age_group");

                    b.Property<DateTime?>("AvatarGeneratedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("avatar_generated_at");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("text")
                        .HasColumnName("avatar_url");

                    b.Property<string>("BigFiveJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("big_five_json")
                        .HasDefaultValueSql("'{}'::jsonb");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<DateTime>("LastUpdated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_updated")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("MbtiType")
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("mbti_type");

                    b.Property<string>("RawSurveyAnswers")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("raw_survey_answers")
                        .HasDefaultValueSql("'{}'::jsonb");

                    b.Property<string>("SpotifyTopTracksJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("spotify_top_tracks_json");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("user_personality_profiles");
                });

            modelBuilder.Entity("MoodLens.ApiGateway.Models.AnalysisFeedback", b =>
                {
                    b.HasOne("MoodLens.ApiGateway.Models.EmotionHistory", "EmotionHistory")
                        .WithMany("FeedbackEntries")
                        .HasForeignKey("HistoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MoodLens.ApiGateway.Models.User", "User")
                        .WithMany("FeedbackEntries")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("EmotionHistory");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MoodLens.ApiGateway.Models.AnalysisRecord", b =>
                {
                    b.HasOne("MoodLens.ApiGateway.Models.EmotionHistory", "EmotionHistory")
                        .WithOne()
                        .HasForeignKey("MoodLens.ApiGateway.Models.AnalysisRecord", "EmotionHistoryId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("MoodLens.ApiGateway.Models.User", "User")
                        .WithMany("AnalysisRecords")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("EmotionHistory");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MoodLens.ApiGateway.Models.EmotionHistory", b =>
                {
                    b.HasOne("MoodLens.ApiGateway.Models.User", "User")
                        .WithMany("EmotionHistories")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("User");
                });

            modelBuilder.Entity("MoodLens.ApiGateway.Models.PersonalityUpdateLog", b =>
                {
                    b.HasOne("MoodLens.ApiGateway.Models.User", "User")
                        .WithMany("PersonalityUpdateLogs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MoodLens.ApiGateway.Models.Recommendation", b =>
                {
                    b.HasOne("MoodLens.ApiGateway.Models.EmotionHistory", "EmotionHistory")
                        .WithMany("Recommendations")
                        .HasForeignKey("HistoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EmotionHistory");
                });

            modelBuilder.Entity("MoodLens.ApiGateway.Models.SavedRecommendation", b =>
                {
                    b.HasOne("MoodLens.ApiGateway.Models.AnalysisRecord", "AnalysisRecord")
                        .WithMany("SavedRecommendations")
                        .HasForeignKey("AnalysisRecordId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MoodLens.ApiGateway.Models.User", "User")
                        .WithMany("SavedRecommendations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AnalysisRecord");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MoodLens.ApiGateway.Models.UserMediaLog", b =>
                {
                    b.HasOne("MoodLens.ApiGateway.Models.User", "User")
                        .WithMany("MediaLogs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MoodLens.ApiGateway.Models.UserPersonalityProfile", b =>
                {
                    b.HasOne("MoodLens.ApiGateway.Models.User", "User")
                        .WithOne("PersonalityProfile")
                        .HasForeignKey("MoodLens.ApiGateway.Models.UserPersonalityProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MoodLens.ApiGateway.Models.AnalysisRecord", b =>
                {
                    b.Navigation("SavedRecommendations");
                });

            modelBuilder.Entity("MoodLens.ApiGateway.Models.EmotionHistory", b =>
                {
                    b.Navigation("FeedbackEntries");

                    b.Navigation("Recommendations");
                });

            modelBuilder.Entity("MoodLens.ApiGateway.Models.User", b =>
                {
                    b.Navigation("AnalysisRecords");

                    b.Navigation("EmotionHistories");

                    b.Navigation("FeedbackEntries");

                    b.Navigation("MediaLogs");

                    b.Navigation("PersonalityProfile");

                    b.Navigation("PersonalityUpdateLogs");

                    b.Navigation("SavedRecommendations");
                });
#pragma warning restore 612, 618
        }
    }
}
